version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "8000:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
